name: Java docs test

on: [pull_request]

jobs:
  docs:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Docs with gradle
        run: ./gradlew javadoc
